### ISSUE TITLE
Footer doesn't always stick to the bottom of the page

### ISSUE THREAD

**Issue by Deborah-Digges** [openhatch/oh-mainline#1437]
For pages that do not have content that fills them entirely, the footer does not stick to the bottom of the page. I've observed this in versions of Chrome and Firefox that I use on the following pages:
(1) https://openhatch.org/account/login/
(2) https://openhatch.org/people/
(3) https://openhatch.org/guide/
It could be fixed with a bit of CSS.

![screenshot from 2014-10-04 19 28 19](https://cloud.githubusercontent.com/assets/3866405/4515775/ff0f7974-4bd1-11e4-8ce2-172fd6de77cc.png)

**Comment by sandeepraju** [comment]
@ehashman This looked like a quick thing to fix but doesn't seem so. Sticking the footer to the bottom is only possible if the height of it is fixed[1] (which is not the case due to the google custom search widget results which varies the footer size). The only other way is to use the new css flex[2] (which is still a working draft - bad idea to use this).

My current fix is here (which doesn't take the expanding google search results into account and hence not raising a PR): https://github.com/sandeepraju/oh-mainline/commit/6d8179a7383fc14624081159efc3f7746988c1db

Ref:
[1] http://getbootstrap.com/examples/sticky-footer/
[2] http://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

Adding the details here so that anyone trying to fix this will have a heads up :)

**Comment by moijes12** [comment]
@willingc I think we should remove the label stat:unread and add label stat:needs-review. Wdyt ?

**Comment by willingc** [comment]
Closed by PR #1586 

Thanks @onceuponatimeforever

**Comment by ehashman** [comment]
I'm concerned this fix has broken the footer in a couple contexts:

![footer](https://cloud.githubusercontent.com/assets/4706131/7159762/74df2e2a-e352-11e4-8e6b-8568f3d3d952.png)

![submit-button](https://cloud.githubusercontent.com/assets/4706131/7159766/7cdfed08-e352-11e4-8c0c-d304df91075b.png)

**Comment by willingc** [comment]
@ehashman Should this be open or closed? :confused:

**Comment by ehashman** [comment]
I just tested this again and it seems to be fixed on Windows, Firefox 39.0.3, so I'll mark it closed. Not sure if a recent PR fixed it.
