### ISSUE TITLE
Nightly data snapshots broken as of Jan. 30

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1533]
See http://inside.openhatch.org/snapshots/ -- for whatever reason we have empty snapshots for the last three days. Someone should investigate.

**Comment by willingc** [comment]
I am going take a wild guess but it may be due to my merge of #1508. Will take a look.

**Comment by willingc** [comment]
If I try `python manage.py snapshot_public_data`, it seems to be writing to a file. Perhaps there's an interaction between this and #1534. Still writing - yawn.

**Comment by willingc** [comment]
@ehashman still writing... Definite yes to #1534.

**Comment by ehashman** [comment]
++, thanks @willingc for looking into this.

**Comment by willingc** [comment]
Additional details on #1534. Running `python manage.py snapshot_public_data` does create a json file so that functionality does work. As an FYI, `mysite/customs/management/commands/snapshot_public_data.py` is the source of the json file creation.

I believe the cron job calls this script nightly `mysite/scripts/snapshot_then_push.sh`. Not sure why it is not working. File size? Change? ?? Please jump in with ideas.

**Comment by ehashman** [comment]
For what it's worth, this issue *does* appear to be resolved (no more 20 byte data snapshots being produced), so I'm going to set this to resolved for now.
