### ISSUE TITLE
Data snapshots are too big

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1534]
This is something @paulproteus and I discussed a while back.

Our current data snapshots are on the order of 18MB when zipped. These are pretty huge and they're not super workable on a low-powered dev environment. As a result of the way the site is written, the first visit to /search/ on a development server can take over a minute to load. Indeed, I could not actually run the development site on my laptop, though it's working fine on this desktop machine I'm currently using.

This could be significantly shortened if we were creating snapshots about a quarter of that size, I believe. Thoughts?

**Comment by willingc** [comment]
Random statistics on current size of snapshots. 
File size (uncompressed): 108318300 Feb  1 14:53 active.json

I loaded the json snapshot into pandas and there are a lot of records (200K+). Here's the breakdown by model:
![screen shot 2015-02-01 at 17 05 28](https://cloud.githubusercontent.com/assets/2680980/5994821/6b74e7de-aa37-11e4-9ce0-8c136b9c558b.png)

**Comment by paulproteus** [comment]
One of the biggest difficulties, I think, is not so much the fact that there are a lot of records, but also that JSON is a very inefficient file format to parse etc.

I haven't benchmarked it yet though -- but my question is, what fraction of time in the `loaddata` step is spent parsing JSON? Or adding stuff to the DB? Also perhaps we can do bulk data loads.

In _fact_ maybe we can do the data load on the server, and then give people a sqlite.db file they can `wget`. That way, when most people download the data, they could skip both the JSON parsing step and the DB insertion step. (For those that want more control, we could continue to publish the JSON dumps.) Note that this strategy would remove any existing local user accounts and other local data. Perhaps for this reason, we should use a different filename for the snapshot DB, so that people aren't tempted to overwrite their real DB, and tell people:

```
To use a snapshot. do the following:
wget http://whatever.whatever/snapshots/current.db -O snapshot.db
echo "USE_SNAPSHOT_DB=True" >> mysite/settings_local.py

When you're doing playing with the local snapshot, remove the
USE_SNAPSHOT_DB line from mysite/settings_local.py
```
or something.

Another difficulty is that /search/ takes _forever_ to load locally with any kind of reasonably-large dataset. This is because /search/ uses ridiculously slow SQL queries, and is in a way separate from the data set that

**Comment by ehashman** [comment]
You trailed off there.

/search/ *does* take forever to load. Related, is there any way to speed up the SQL queries?

**Comment by phildini** [comment]
What is in the snapshots? Is it a full set of all data from forever, or just a slice? It seems like trimming the time-period slice might alleviate some problems in the short term.

In the long term, I really like @paulproteus' idea of being able to fetch an external sqlite db, and running the server with that. Perhaps even adding the `wget` to the getting started doc would be a good step.

Forgive my ignorance and lack of deep research on the issue.

**Comment by onceuponatimeforever** [comment]
Extra helpful background info
=====================
from https://openhatch.org/wiki/Importing_a_data_snapshot, the code is — https://github.com/openhatch/oh-mainline/blob/master/mysite/customs/management/commands/snapshot_public_data.py

**Comment by willingc** [comment]
@onceuponatimeforever @paulproteus  Yay!

**Comment by ehashman** [comment]
In order to set this resolved, I expected that either small datasets would be available on inside.openhatch.org, or that I could use some kind of tool to create a small data set. I clicked on @onceuponatimeforever's links but I don't see either of these solutions. Could someone please advise?
