### ISSUE TITLE
Get to know the shell mission broken link

### ISSUE THREAD

**Issue by darelb** [openhatch/oh-mainline#1575]
On the [Missions](http://openhatch.org/missions/) page, the `Get to know about: "The Shell"` link is broken. The following address is the target of the link but no page is found at the address.

http://openhatch.org/missions/shell/about

**Comment by willingc** [comment]
@darelb Thank you for reporting this issue. I'm sorry that the link is not redirecting properly. Please do ask on IRC if you have any questions about the shell before this issue is resolved. Thanks!

OpenHatch developers: It looks like there is an issue with #1542 with the Shell 'Go' link directing to a missions/shell/about which is a 404. I did a quick scan of the source code and I'm wondering if using `missions/shell/about` instead of using `missions/shell` is causing `oh-mainline/mysite/missions/base/views.py` to get confused when handling the URL. 

@vipul-sharma20: Since you created the mission and I want users to be able to learn from it ( :smiley:  ), would you mind taking a look at this? Thanks.

**Comment by eeshangarg** [comment]
Hi @willingc, @darelb!

I also took a look at this and found out that not only does the Shell mission lead to a 404 but the pipvirtualenv mission also leads to a 404. I updated my local oh-mainline repo and they seem to be working fine when I visit the missions on the development server on my computer. @darelb: Thanks a lot for reporting this!

@willingc: Hello, ma'am! The main page for the pipvirtualenv mission uses the URL missions/pipvirtualenv instead of something like missions/pipvirtualenv/about, but still the "Go" link leads to a 404. Admittedly, I am confused as to what's causing this; I'll try and go through the code again and and try my best to find a solution. Can't wait to see you at PyCon, ma'am! See you soon! :-)

Warm regards,
Eeshan Garg

**Comment by vipul-sharma20** [comment]
Hi @willingc @eeshangarg 

@eeshangarg yes, you are right. Both the missions lead to 404 when clicked on "Go". I looked in the code to see what is causing this but I am also confused. Still, I will go through the code again and see what is wrong :)

**Comment by willingc** [comment]
@eeshangarg @vipul-sharma20 Well they are both new missions so I'm going to guess that the root cause is with the url handling. I would recommend going back and looking at an earlier PR for one of the other oppia missions and see if there is something different about 'urls.py' or 'missions.base' files or views vs the new missions.

**Comment by su7edja** [comment]
Resolved.
