### ISSUE TITLE
Prune django_session and sessionprofile_sessionprofile tables

### ISSUE THREAD

**Issue by jwm** [openhatch/oh-mainline#1591]
It seems the `django_session` and `sessionprofile_sessionprofile` tables aren't pruned, since both have ~8M rows.

**Comment by onceuponatimeforever** [comment]
I've researched the problem statement; Django official docs has this recommendation: https://docs.djangoproject.com/en/1.5/topics/http/sessions/#clearing-the-session-store

What bash script gets called everyday that which I can simply add in `./manage.py clearsessions`? @paulproteus I don;t know the answer to that question  because I don't have prod server access to be able to log in and find the crontab.
