### ISSUE TITLE
No Any option for "Just bugs labeled..."

### ISSUE THREAD

**Issue by ableman** [openhatch/oh-mainline#1592]
![image](https://cloud.githubusercontent.com/assets/4017467/7127191/5b96f0e6-e1f5-11e4-80c2-0ab792d24e0d.png)

All the other columns have an any option, the "Just bugs labeled..." doesn't, which makes it impossible to broaden your search if you click "documentation".

More generally, I think a better flow would be to be able to "unclick" rather than have an "Any" option appear, but that's probably harder to do.

**Comment by ehashman** [comment]
One thing I've noticed is that the "any" option only seems to show up when one has clicked on "bitesize" or "documentation", which is not what I'd expect for UX, but that's alright. I've confirmed this fix is working! Just want to note that behaviour for the record.

Thanks for catching that the "any" option wasn't showing up in this column due to a typo!

**Comment by shaunagm** [comment]
I don't love the way the any option works generally, see this issue: https://github.com/openhatch/oh-mainline/issues/1594
