### ISSUE TITLE
Footer bar height causes git mission text to be obscured 

### ISSUE THREAD

**Issue by willingc** [openhatch/oh-mainline#1641]
Footer bar is not displaying correctly in the git training mission landing page. The footer's height is too large and overwrites the mission text. The screenshot was taken using most recent version of Chrome.

![screen shot 2015-04-28 at 7 02 45 am](https://cloud.githubusercontent.com/assets/2680980/7371325/05bead04-ed75-11e4-8dbc-484d739a57b7.png)

This may be related to #1437.

**Comment by paulproteus** [comment]
For what it's worth, this is still true with the latest changes.

**Comment by willingc** [comment]
This is still an issue with latest Google Chrome version.  Oddly enough, it seems fine on Firefox. Stubborn footer :(

Chrome
![screen shot 2015-05-06 at 5 00 30 pm](https://cloud.githubusercontent.com/assets/2680980/7506221/fbd21fee-f411-11e4-9885-cc2873925acc.png)

Firefox
![screen shot 2015-05-06 at 5 03 38 pm](https://cloud.githubusercontent.com/assets/2680980/7506224/0369004c-f412-11e4-8437-d487609d64c2.png)

**Comment by willingc** [comment]
@paulproteus I did a little investigating on this based on your suggestion on IRC re: resetting the cache in Chrome. That did fix the overlapping footer. Is there a way in javascript or something else that will trigger a reload of the footer after a change is deployed?

**Comment by NPrescott** [comment]
JavaScript can't force a browser to clear its cache, so far as I know. Possible solutions would be to
 - disable caching at the webserver, Nginx would use something like `expires           0;` in the server block
   - not ideal because you lose all the benefits of caching
 - serve static files through Django and use something like [ManifestStaticFileStorage](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) to create unique URIs for each change to the file
   - not ideal because you lose the speed associated with caching at the proxy/web server rather than the application server

**Comment by NPrescott** [comment]
I know I've mentioned this before ( and still haven't found time to track it down ) but I believe the footer on the git mission page is off-center because of a missing `</div>` tag on the `<div id="container">`. I _think_ it was removed [here](https://github.com/openhatch/oh-mainline/commit/1fa255d520f1a48316f2065cffbd8c265c2e0143#diff-2c057cdb9dbc27e65838df9cef619929L158). You can check with the W3C validator [here](http://validator.w3.org/check?uri=http%3A%2F%2Fopenhatch.org%2Fmissions%2Fgit&charset=%28detect+automatically%29&doctype=Inline&group=0).

**Comment by willingc** [comment]
@NPrescott Thanks for the additional insights and PR. I will do my best to review the PR in the next day. If someone else wishes to review before then, please do so.  Thanks again :)

**Comment by brittag** [comment]
I was looking at this today since it slightly hides our nice promotional stuff on the bottom of the homepage - tiny nudge for somebody to look at this. :)

**Comment by NPrescott** [comment]
This slipped my mind entirely, I think I may have deleted the branch on GH after I botched a commit but all should be well and ready for review now. I've got an open PR now against this with the fix I mentioned previously.  Thanks for the nudge @brittag.

**Comment by willingc** [comment]
Closed by PR #1668
