### ISSUE TITLE
Adding a drop down login on the main page

### ISSUE THREAD

**Issue by NPrescott** [openhatch/oh-mainline#1654]
[This original issue](https://github.com/openhatch/oh-mainline/issues/451) brought about a feature request, distilled down from [this conversation](http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2011-04-26#i_2616885).

> We'd love a login drop-down from the main openhatch login link, [as described here](http://uxmovement.com/forms/dropdown-login-boxes-for-faster-login)
> 
> We should have an off-site login page that will contain exactly the same content, [like this page](http://gawker.zendesk.com/access/unauthenticated?return_to=http%3A%2F%2Fgawker.zendesk.com%2Flogin)
> 
> Sign-up and login pages are exactly the same, so merge them.
>  1. If you have an account already then you have the option to add / merge that new login type with your current openhatch account.
> 
>  1. If you don't have an account already then using whatever login type will create a new openhatch account.
> 
>  1. Things to validate duplicate users should be location or username, and you can't login using another login type that has been already been used with an existing account. (need more suggestions...)
> 
> so I will get a couple of mockups together...
>  - for on-site drop-down login
>  - for off-site (Roundup & wiki)

@paulhomebus's mockup:
![login-mockup](https://cloud.githubusercontent.com/assets/4661088/7742789/f75a7a22-ff58-11e4-8178-f1dc1290ccb2.png)

**Comment by willingc** [comment]
Hi @NPrescott, Thanks for opening the issue :)

**Comment by moijes12** [comment]
I'd like to work on this.

**Comment by willingc** [comment]
@moijes12 That's great.

**Comment by palbakulich** [comment]
Looking forward to seeing this implemented!

**Comment by Deborah-Digges** [comment]
hi @moijes12 . If possible, I would love to help on this :smiley:

**Comment by moijes12** [comment]
@Deborah-Digges Maybe you can start working on it and I'll help in testing. I'm still learning JavaScript and Front-end stuff and improvements to OpenHatch shouldn't stop because of that :) .

**Comment by willingc** [comment]
Sounds like a good plan :)

**Comment by Deborah-Digges** [comment]
@moijes12 @willingc that sounds great :D I'll keep you posted on the status of this feature !

**Comment by Deborah-Digges** [comment]
I've read through the IRC logs and the roundup bug and I just want to confirm my understanding of the requirements:
From the homepage, on clicking the login/signup link, we are directed to the http://openhatch.org/account/login/ page which is to look like @paulhomebus's mockup. 
This page will have no header and footer.

**Comment by palbakulich** [comment]
@Deborah-Digges... that was the suggestion by @paulproteus.
If we could use the drop-down method as originally suggested @  http://uxmovement.com/forms/dropdown-login-boxes-for-faster-login.   -- That would be awesome!!

Instead of using a dropdown select box as in the original mockup, just use icons for the openid / oauth providers, with the relatedly stuff at the bottom for those who prefer.

The signup could be in a seperate dropdown 'tab'.

Making myself available on IRC to further discuss. IRC username: _x0pal0x_

**Comment by Deborah-Digges** [comment]
@palbakulich @paulproteus is this still under discussion? If so, I'd love to meet you up on IRC. I'm still a little unclear as to the design :-)

**Comment by willingc** [comment]
I am going to retag this issue as deferred since it is a feature enhancement. If someone or several want to claim the issue (since there was interest), please let me know and we can assign the issue and determine what's needed. Alternatively, this can be addressed after the OpenHatch team moves forward with the Strategic Technical Planning for 2015-16.

**Comment by Deborah-Digges** [comment]
@willingc :+1: That definitely sounds good. let's add it to the Planning and see where it figures in our priorities
