### ISSUE TITLE
Login page automatically redirects me to sign in with a Google Account

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1680]
Steps to reproduce:

1. Go to http://openhatch.org.
2. Begin to log in by clicking "log in / **sign up**" in the top nav bar.
3. The login page loads, and then immediately redirects me to a Google login. No bueno :(

**Comment by staranjeet** [comment]
I am not able to reproduce the error. Every time I click on login/sign up it redirects me to a page where all the login providers are listed.

**Comment by paulproteus** [comment]
For what it's worth, I think the login code stores a cookie that makes it
default to the last provider used.

**Comment by ehashman** [comment]
I'm encountering this bug on every system I'm trying to log in on, despite having never used Google Account to log in. I'm using Firefox (probably various different versions) on Linux. Just tried again, still there :\

**Comment by paulproteus** [comment]
I can't reproduce this in a Chromium in incognito mode. @ehashman do you have a cookie called `openid_provider`? It seems in `mysite/static/openid/js/openid-jquery.js` we check this.

If we conclude that's what's going on for you, @ehashman , then we can figure out how to best solve it.

**Comment by waseem18** [comment]
The problem is with the cookie `openid_provider`. When a user logins to OH, a cookie `openid_provider` is being created which redirects the future users to the same provider which the initial user used to log in.

@ehashman `I'm encountering this bug on every system I'm trying to log in on` . That's because someone might have logged in through that system earlier using Google which created a cookie (lasting 6 months) and is redirecting the future users to Google.

@paulproteus The cookie is what causes the problem. I guess reducing the cookie life time drastically to just a couple to hours can reduce the problem to some extent. Removing the cookie can be a good choice too.

**Comment by ehashman** [comment]
I'd agree that it's probably a cookie problem---just tested on my cleanly installed system and I'm unable to reproduce.

I think we should try for a more user-friendly fix than "remove the cookie" because that's fine for me but it might not be for a newbie.

**Comment by paulproteus** [comment]
The simplest fix might be to patch the JS code to not look at this cookie,
fwiw. People can probably remember what account type they had.
>
>

**Comment by waseem18** [comment]
@paulproteus Tried to fix the issue by removing the cookie (openid_provider) and cookie related operations (readCookie, setCookie). PR  - #1690

**Comment by ehashman** [comment]
Oh, I think this was resolved by the PR above. Thanks again @waseem18 !
