### ISSUE TITLE
Scraping is currently broken

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1713]
According to http://inside.openhatch.org/crawl-logs/ we haven't had a successful bug scrape since Sep. 27. As for why: according to the [scrape logs](http://inside.openhatch.org/crawl-logs/scrapy.2015-09-28.CoNX.log), django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

@jwm is this Heroku migration-related? @paulproteus would you know where to start in debugging/fixing this? I'm assuming you are the keeper of all the secret keys.

**Comment by jwm** [comment]
@ehashman I updated `local_settings.py` appropriately on linode2, so this should be successful tonight. I'll check on it in the morning.

**Comment by jwm** [comment]
Looks like `SECRET_KEY` is set correctly on linode2 now, but the crawl is failing because the tracker list it retrieves from https://openhatch.org/+api/v1/customs/tracker_model/just_stale=yes&format=yaml&limit=500 is exceeding Heroku's allowed request time (https://devcenter.heroku.com/articles/request-timeout).

Retrieving only 50 trackers (instead of 500) still takes ~20 seconds, so we might need to overhaul the queries at https://github.com/openhatch/oh-mainline/blob/master/mysite/customs/api.py#L55-L79 or have this support pagination so the crawl can retrieve trackers in batches.
