### ISSUE TITLE
Projects view has unsafe caching. We should change that.

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#666]
<b>Comment by <a href='https://openhatch.org/people/aldeka/'>aldeka</a>:</b><dl><dd>Every time you unsafely cache a page that devs want to work on, you make baby
Jesus cry.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>Can we flesh out the details on this bug to make it more fixable for a new contributor?
I may be interested in fixing this, if I can get a better handle on it.
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  aldeka, palhmbs, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>351</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue351'>view archived page</a>)
Last modified: <b>2011-07-02.20:25:53</b>

**Comment by NPrescott** [comment]
Digging through the bug backlog a bit here. I'm not sure I understand the original complaint, caching _is_ typically annoying in a development environment, but there are now tests in place that rely on/test the cache functionality. It's simple enough to disable caching in development with the following patch:

```patch
diff --git a/mysite/settings.py b/mysite/settings.py
index 561d8d2..34f5c05 100644
--- a/mysite/settings.py
+++ b/mysite/settings.py
@@ -266,12 +266,20 @@ DEFAULT_FROM_EMAIL = 'all@openhatch.org'
 EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
 EMAIL_PORT = 1025

-CACHES = {
-    'default': {
-        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
-        'LOCATION': 'openhatch'
+if DEBUG:
+    CACHES = {
+        'default': {
+            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
+        }
     }
-}
+else:
+    CACHES = {
+        'default': {
+            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
+            'LOCATION': 'openhatch'
+        }
+    }
+
```
It will however break the following two tests (unsurprisingly):
 - test_with_lock_contention (mysite.customs.tests.BlogCache)
 - test_unicode_strings_get_cached (mysite.base.tests.GeocoderCanCache)

```
======================================================================
FAIL: test_unicode_strings_get_cached (mysite.base.tests.GeocoderCanCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nolan/Projects/others/oh-mainline/mysite/base/tests.py", line 224, in test_unicode_strings_get_cached
    + json)
AssertionError: Geocoded location in json was not cached; it now equals {"key": "if caching works we should never get this value", "is_inaccessible": false}

======================================================================
FAIL: test_with_lock_contention (mysite.customs.tests.BlogCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nolan/Projects/others/oh-mainline/mysite/customs/tests.py", line 149, in test_with_lock_contention
    self.assertEqual(entries, self.blog_fetcher_version_1())
AssertionError: 'this-data-is-also-fake' != 'this-data-is-fake'
```
This is only the case with `DEBUG = True` set to `False` all tests pass.

So it seems a decision needs to be made as to whether this is a bug, or expected functionality. I haven't been able to work out a clever way to swap the cache within just those two test cases; fiddling with the setting doesn't work, I'm not sure if it's because of how the cache is decorating the view function and may have already been initialized. Point being, it's easy to disable caching in development, but it breaks two tests if `DEBUG = True` - thoughts?

**Comment by willingc** [comment]
@NPrescott Thank you for your detailed research and write up. I agree with the question you raised on IRC to either file a PR or close this issue.

I'm inclined to close this issue. Perhaps my configuration differs from yours but I am seeing these two tests pass when DEBUG = True. Are you still seeing test failures?

What are your thoughts on closing this issue?

**Comment by NPrescott** [comment]
@willingc - I should have been clearer, the two tests fail with `DEBUG=True` only when the above patch is applied. Otherwise they are currently passing. 

I would vote to close the issue from what I have seen; I'm not sure what disabling caching buys developers at this point (other than maybe being a more standard practice I suppose?). I think it would unnecessarily complicate running the tests if we were to require a specific settings configuration.

**Comment by willingc** [comment]
@NPrescott - That makes more sense re: patch and tests.

I agree with your recommendation to close this issue, and will do so now.

Thanks for the detailed feedback and work that you have put into researching and resolving this issue. In the future, please feel free to share your thoughts in the issue comments if you think an issue should be closed or a PR generated. :+1:  :penguin:
